<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Profile</title>
    <!--CSS link doesnt work for this page-->
    <link rel="stylesheet" href="CSS/profile.css">
</head>
<body>
    <ul>
        <style>
            ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
                background-color: #333;
            }

            li {
                float: left;
            }

            li a {
                display: block;
                color: white;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

            li a:hover {
                background-color: #111;
            }
        </style>
        <li><a href="home.html">Home</a></li>
        <li><a href="topics.html">Your Topics</a></li>
        <li><a href="profile.html">Profile</a></li>
    </ul>
    <div class="container">
        <header>
            <style>
                h1 {
                    text-align: center;
                }
            </style>
            <h1>Your Username</h1>
        </header>
        <div id="content"> 
            <p>Your email goes here</p>
            <p>Your member since date goes here</p>
            <p>Your number of articles read goes here</p>
            <p>Your bio goes here</p>
            <p>Your location goes here</p>
            <p>Your interests go here</p>
            <p>Your number of reviews goess here</p>
            <p>Your number of subscriptions goes here:</p>
            <p>With</p>
            <p>An</p>
            <p>Accompanying</p>
            <p>List</p>
            <p>Of</p>
            <p>Topics</p>
            <p>You're</p>
            <p>Subscribed</p>
            <p>To</p>
        </div>
</body>
</html>
